package com.sforce.soap.partner;

/**
 * Generated by ComplexTypeCodeGenerator.java. Please do not edit.
 */
public class DescribeAvailableQuickActions_element implements com.sforce.ws.bind.XMLizable {

    /**
     * Constructor
     */
    public DescribeAvailableQuickActions_element() {}

    /**
     * element : parentType of type {http://www.w3.org/2001/XMLSchema}string
     * java type: java.lang.String
     */
    private static final com.sforce.ws.bind.TypeInfo parentType__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:partner.soap.sforce.com","parentType","http://www.w3.org/2001/XMLSchema","string",1,1,true);

    private boolean parentType__is_set = false;

    private java.lang.String parentType;

    public java.lang.String getParentType() {
      return parentType;
    }

    public void setParentType(java.lang.String parentType) {
      this.parentType = parentType;
      parentType__is_set = true;
    }

    /**
     */
    @Override
    public void write(javax.xml.namespace.QName __element,
        com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper)
        throws java.io.IOException {
      __out.writeStartTag(__element.getNamespaceURI(), __element.getLocalPart());
      writeFields(__out, __typeMapper);
      __out.writeEndTag(__element.getNamespaceURI(), __element.getLocalPart());
    }

    protected void writeFields(com.sforce.ws.parser.XmlOutputStream __out,
         com.sforce.ws.bind.TypeMapper __typeMapper)
         throws java.io.IOException {
       __typeMapper.writeString(__out, parentType__typeInfo, parentType, parentType__is_set);
    }

    @Override
    public void load(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __typeMapper.consumeStartTag(__in);
      loadFields(__in, __typeMapper);
      __typeMapper.consumeEndTag(__in);
    }

    protected void loadFields(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
        __in.peekTag();
        if (__typeMapper.verifyElement(__in, parentType__typeInfo)) {
            setParentType(__typeMapper.readString(__in, parentType__typeInfo, java.lang.String.class));
        }
    }

    @Override
    public String toString() {
      java.lang.StringBuilder sb = new java.lang.StringBuilder();
      sb.append("[DescribeAvailableQuickActions_element ");
      sb.append(" parentType=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(parentType)+"'\n");
      sb.append("]\n");
      return sb.toString();
    }
}
