package com.sforce.soap.partner;

/**
 * Generated by ComplexTypeCodeGenerator.java. Please do not edit.
 */
public class PerformQuickActionResult implements com.sforce.ws.bind.XMLizable {

    /**
     * Constructor
     */
    public PerformQuickActionResult() {}

    /**
     * element : created of type {http://www.w3.org/2001/XMLSchema}boolean
     * java type: boolean
     */
    private static final com.sforce.ws.bind.TypeInfo created__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:partner.soap.sforce.com","created","http://www.w3.org/2001/XMLSchema","boolean",1,1,true);

    private boolean created__is_set = false;

    private boolean created;

    public boolean getCreated() {
      return created;
    }

    public boolean isCreated() {
      return created;
    }

    public void setCreated(boolean created) {
      this.created = created;
      created__is_set = true;
    }

    /**
     * element : errors of type {urn:partner.soap.sforce.com}Error
     * java type: com.sforce.soap.partner.Error[]
     */
    private static final com.sforce.ws.bind.TypeInfo errors__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:partner.soap.sforce.com","errors","urn:partner.soap.sforce.com","Error",0,-1,true);

    private boolean errors__is_set = false;

    private com.sforce.soap.partner.Error[] errors = new com.sforce.soap.partner.Error[0];

    public com.sforce.soap.partner.Error[] getErrors() {
      return errors;
    }

    public void setErrors(com.sforce.soap.partner.Error[] errors) {
      this.errors = errors;
      errors__is_set = true;
    }

    /**
     * element : feedItemIds of type {urn:partner.soap.sforce.com}ID
     * java type: java.lang.String[]
     */
    private static final com.sforce.ws.bind.TypeInfo feedItemIds__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:partner.soap.sforce.com","feedItemIds","urn:partner.soap.sforce.com","ID",0,-1,true);

    private boolean feedItemIds__is_set = false;

    private java.lang.String[] feedItemIds = new java.lang.String[0];

    public java.lang.String[] getFeedItemIds() {
      return feedItemIds;
    }

    public void setFeedItemIds(java.lang.String[] feedItemIds) {
      this.feedItemIds = feedItemIds;
      feedItemIds__is_set = true;
    }

    /**
     * element : ids of type {urn:partner.soap.sforce.com}ID
     * java type: java.lang.String[]
     */
    private static final com.sforce.ws.bind.TypeInfo ids__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:partner.soap.sforce.com","ids","urn:partner.soap.sforce.com","ID",0,-1,true);

    private boolean ids__is_set = false;

    private java.lang.String[] ids = new java.lang.String[0];

    public java.lang.String[] getIds() {
      return ids;
    }

    public void setIds(java.lang.String[] ids) {
      this.ids = ids;
      ids__is_set = true;
    }

    /**
     * element : success of type {http://www.w3.org/2001/XMLSchema}boolean
     * java type: boolean
     */
    private static final com.sforce.ws.bind.TypeInfo success__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:partner.soap.sforce.com","success","http://www.w3.org/2001/XMLSchema","boolean",1,1,true);

    private boolean success__is_set = false;

    private boolean success;

    public boolean getSuccess() {
      return success;
    }

    public boolean isSuccess() {
      return success;
    }

    public void setSuccess(boolean success) {
      this.success = success;
      success__is_set = true;
    }

    /**
     */
    @Override
    public void write(javax.xml.namespace.QName __element,
        com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper)
        throws java.io.IOException {
      __out.writeStartTag(__element.getNamespaceURI(), __element.getLocalPart());
      writeFields(__out, __typeMapper);
      __out.writeEndTag(__element.getNamespaceURI(), __element.getLocalPart());
    }

    protected void writeFields(com.sforce.ws.parser.XmlOutputStream __out,
         com.sforce.ws.bind.TypeMapper __typeMapper)
         throws java.io.IOException {
       __typeMapper.writeBoolean(__out, created__typeInfo, created, created__is_set);
       __typeMapper.writeObject(__out, errors__typeInfo, errors, errors__is_set);
       __typeMapper.writeObject(__out, feedItemIds__typeInfo, feedItemIds, feedItemIds__is_set);
       __typeMapper.writeObject(__out, ids__typeInfo, ids, ids__is_set);
       __typeMapper.writeBoolean(__out, success__typeInfo, success, success__is_set);
    }

    @Override
    public void load(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __typeMapper.consumeStartTag(__in);
      loadFields(__in, __typeMapper);
      __typeMapper.consumeEndTag(__in);
    }

    protected void loadFields(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
        __in.peekTag();
        if (__typeMapper.verifyElement(__in, created__typeInfo)) {
            setCreated(__typeMapper.readBoolean(__in, created__typeInfo, boolean.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, errors__typeInfo)) {
            setErrors((com.sforce.soap.partner.Error[])__typeMapper.readObject(__in, errors__typeInfo, com.sforce.soap.partner.Error[].class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, feedItemIds__typeInfo)) {
            setFeedItemIds((java.lang.String[])__typeMapper.readObject(__in, feedItemIds__typeInfo, java.lang.String[].class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, ids__typeInfo)) {
            setIds((java.lang.String[])__typeMapper.readObject(__in, ids__typeInfo, java.lang.String[].class));
        }
        __in.peekTag();
        if (__typeMapper.verifyElement(__in, success__typeInfo)) {
            setSuccess(__typeMapper.readBoolean(__in, success__typeInfo, boolean.class));
        }
    }

    @Override
    public String toString() {
      java.lang.StringBuilder sb = new java.lang.StringBuilder();
      sb.append("[PerformQuickActionResult ");
      sb.append(" created=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(created)+"'\n");
      sb.append(" errors=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(errors)+"'\n");
      sb.append(" feedItemIds=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(feedItemIds)+"'\n");
      sb.append(" ids=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(ids)+"'\n");
      sb.append(" success=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(success)+"'\n");
      sb.append("]\n");
      return sb.toString();
    }
}
